[package]
name = "aoc-2024"
version = "0.1.0"
description = "Solutions to Advent of Code (2024) problems."
edition = "2024"

[dependencies]
aoc-common = { path = "../common" }
colored = "2.1.0"
regex = "1.11.1"